from collections import OrderedDict
from collections.abc import Callable
from pathlib import Path
from unittest.mock import patch

import pytest

from wikidict import context
from wikidict.render import parse_word
from wikidict.stubs import Definitions

LANG = __name__.split("_", 1)[1]


@pytest.fixture(scope="module", autouse=True)
def setup_lua_ctx() -> None:
    with patch.dict("os.environ", {"CWD": str(Path(context.__file__).parent.parent)}):
        assert context.reset(LANG)


@pytest.mark.parametrize(
    "word, pronunciations, etymology, definitions, variants, reverse_variants",
    [
        (
            "Avusturyalılık'ın",
            ["/a.vus.ˈtuɾ.ja.lɯ.ɫɯ.ˈ‿ɯn/"],
            [],
            {},
            ["Avusturyalılık"],
            [],
        ),
        (
            "bulmaca",
            [],
            [],
            {
                "Ad": [
                    "(<i>oyun</i>) çeşitli biçimlerde düzenlenen ve düşündürerek, aratarak buldurmayı amaç edinen oyun"
                ]
            },
            [],
            [],
        ),
        (
            "bulmacamda",
            [],
            [],
            {},
            ["bulmaca"],
            [],
        ),
        (
            "Estonyalı",
            [],
            [],
            {"Ön Ad": ["(<i>milliyetler</i>) ökeni Estonya olan kimse", "Kökeni Estonya olan."]},
            [],
            [],
        ),
        (
            "iğne yaprak",
            ["/ɪ‿.ˈnɛ jɑp.ɾɑc/"],
            [],
            {"Ad": ["(<i>bitki anatomisi</i>) çam türlerinde görülen, ince uzun, sivri uçlu yaprak"]},
            [],
            [
                "iğne yapraklar",
                "iğne yapraklara",
                "iğne yapraklarda",
                "iğne yapraklardan",
                "iğne yaprakları",
                "iğne yapraklarım",
                "iğne yapraklarıma",
                "iğne yapraklarımda",
                "iğne yapraklarımdan",
                "iğne yapraklarımı",
                "iğne yapraklarımın",
                "iğne yapraklarımız",
                "iğne yapraklarımıza",
                "iğne yapraklarımızda",
                "iğne yapraklarımızdan",
                "iğne yapraklarımızı",
                "iğne yapraklarımızın",
                "iğne yaprakların",
                "iğne yapraklarına",
                "iğne yapraklarında",
                "iğne yapraklarından",
                "iğne yapraklarını",
                "iğne yapraklarının",
                "iğne yapraklarınız",
                "iğne yapraklarınıza",
                "iğne yapraklarınızda",
                "iğne yapraklarınızdan",
                "iğne yapraklarınızı",
                "iğne yapraklarınızın",
                "iğne yaprakta",
                "iğne yapraktan",
                "iğne yaprağa",
                "iğne yaprağı",
                "iğne yaprağım",
                "iğne yaprağıma",
                "iğne yaprağımda",
                "iğne yaprağımdan",
                "iğne yaprağımı",
                "iğne yaprağımın",
                "iğne yaprağımız",
                "iğne yaprağımıza",
                "iğne yaprağımızda",
                "iğne yaprağımızdan",
                "iğne yaprağımızı",
                "iğne yaprağımızın",
                "iğne yaprağın",
                "iğne yaprağına",
                "iğne yaprağında",
                "iğne yaprağından",
                "iğne yaprağını",
                "iğne yaprağının",
                "iğne yaprağınız",
                "iğne yaprağınıza",
                "iğne yaprağınızda",
                "iğne yaprağınızdan",
                "iğne yaprağınızı",
                "iğne yaprağınızın",
            ],
        ),
        (
            "kanat açmak",
            [],
            [],
            {"Eylem": ["birini korumak, himaye etmek"]},
            [],
            [],
        ),
        (
            "Karaburç",
            [],
            [],
            {
                "Özel Ad": [
                    "(<i>köyler</i>) Gaziantep ili Nizip ilçesine bağlı bir köy.",
                    "(<i>köyler</i>) İzmir ili Kiraz ilçesine bağlı bir köy.",
                    "(<i>köyler</i>) Nevşehir ili Hacıbektaş ilçesine bağlı bir köy.",
                    "(<i>köyler</i>) Samsun ili Bafra ilçesine bağlı bir köy.",
                ]
            },
            [],
            [],
        ),
        (
            "payandalama",
            [],
            [],
            {},
            ["payandalamak"],
            [
                "payandalamada",
                "payandalamadan",
                "payandalamalar",
                "payandalamalara",
                "payandalamalarda",
                "payandalamalardan",
                "payandalamaları",
                "payandalamalarım",
                "payandalamalarıma",
                "payandalamalarımda",
                "payandalamalarımdan",
                "payandalamalarımı",
                "payandalamalarımın",
                "payandalamalarımız",
                "payandalamalarımıza",
                "payandalamalarımızda",
                "payandalamalarımızdan",
                "payandalamalarımızı",
                "payandalamalarımızın",
                "payandalamaların",
                "payandalamalarına",
                "payandalamalarında",
                "payandalamalarından",
                "payandalamalarını",
                "payandalamalarının",
                "payandalamalarınız",
                "payandalamalarınıza",
                "payandalamalarınızda",
                "payandalamalarınızdan",
                "payandalamalarınızı",
                "payandalamalarınızın",
                "payandalamam",
                "payandalamama",
                "payandalamamda",
                "payandalamamdan",
                "payandalamamı",
                "payandalamamın",
                "payandalamamız",
                "payandalamamıza",
                "payandalamamızda",
                "payandalamamızdan",
                "payandalamamızı",
                "payandalamamızın",
                "payandalaman",
                "payandalamana",
                "payandalamanda",
                "payandalamandan",
                "payandalamanı",
                "payandalamanın",
                "payandalamanız",
                "payandalamanıza",
                "payandalamanızda",
                "payandalamanızdan",
                "payandalamanızı",
                "payandalamanızın",
                "payandalaması",
                "payandalamasına",
                "payandalamasında",
                "payandalamasından",
                "payandalamasını",
                "payandalamasının",
                "payandalamaya",
                "payandalamayı",
            ],
        ),
        (
            "sarman",
            [],
            [],
            {"Ad": ["(<i>kedigiller</i>) Sarı tüylü kedi."], "Ön Ad": ["Azman, iri."]},
            ["sarma"],
            [
                "sarmana",
                "sarmanda",
                "sarmandan",
                "sarmanlar",
                "sarmanlara",
                "sarmanlarda",
                "sarmanlardan",
                "sarmanları",
                "sarmanlarım",
                "sarmanlarıma",
                "sarmanlarımda",
                "sarmanlarımdan",
                "sarmanlarımı",
                "sarmanlarımın",
                "sarmanlarımız",
                "sarmanlarımıza",
                "sarmanlarımızda",
                "sarmanlarımızdan",
                "sarmanlarımızı",
                "sarmanlarımızın",
                "sarmanların",
                "sarmanlarına",
                "sarmanlarında",
                "sarmanlarından",
                "sarmanlarını",
                "sarmanlarının",
                "sarmanlarınız",
                "sarmanlarınıza",
                "sarmanlarınızda",
                "sarmanlarınızdan",
                "sarmanlarınızı",
                "sarmanlarınızın",
                "sarmanı",
                "sarmanım",
                "sarmanıma",
                "sarmanımda",
                "sarmanımdan",
                "sarmanımı",
                "sarmanımın",
                "sarmanımız",
                "sarmanımıza",
                "sarmanımızda",
                "sarmanımızdan",
                "sarmanımızı",
                "sarmanımızın",
                "sarmanın",
                "sarmanına",
                "sarmanında",
                "sarmanından",
                "sarmanını",
                "sarmanının",
                "sarmanınız",
                "sarmanınıza",
                "sarmanınızda",
                "sarmanınızdan",
                "sarmanınızı",
                "sarmanınızın",
            ],
        ),
    ],
)
def test_parse_word(
    word: str,
    pronunciations: list[str],
    etymology: list[Definitions],
    definitions: Definitions,
    variants: list[str],
    reverse_variants: list[str],
    page: Callable[[str, str], str],
) -> None:
    """Test the sections finder and definitions getter."""
    code = page(word, LANG)
    details = parse_word(word, code, LANG, force=True)
    assert details
    assert pronunciations == details.pronunciations
    assert OrderedDict(definitions) == details.definitions
    assert etymology == details.etymology
    assert variants == details.variants
    assert reverse_variants == details.reverse_variants
