from collections.abc import Callable
from pathlib import Path
from unittest.mock import patch

import pytest

from wikidict import context
from wikidict.render import parse_word
from wikidict.stubs import Definitions


@pytest.fixture(scope="module", autouse=True)
def setup_lua_ctx() -> None:
    with patch.dict("os.environ", {"CWD": str(Path(context.__file__).parent.parent)}):
        assert context.reset("lt")


@pytest.mark.parametrize(
    "word, pronunciations, genders, etymology, definitions, variants, reverse_variants",
    [
        (
            "abalienacija",
            [],
            ["f"],
            ["(<i>lot.</i>&#32;abalienatio)"],
            {"Daiktavardis": ["(<i>Ekonomika</i>) - turto nusavinimas arba perleidimas."]},
            [],
            [
                "abalienacijai",
                "abalienacijas",
                "abalienacijoje",
                "abalienacijomis",
                "abalienacijoms",
                "abalienacijos",
                "abalienacijose",
                "abalienaciją",
                "abalienacijų",
            ],
        ),
        (
            "Antigva ir Barbuda",
            [],
            ["f"],
            [],
            {
                "Daiktavardis": [
                    "(<i>Valstybės</i>)&#32;- salų valstybė rytinėje Karibų jūros dalyje, Mažųjų Antilų salyne, šalia Atlanto vandenyno."
                ]
            },
            [],
            [],
        ),
        (
            "dengti",
            [],
            [],
            ["<= dengti, dengia, dengė"],
            {
                "Veiksmažodis": [
                    "dėti, kloti ant viršaus",
                    ("<i><b>Dengė</b> puodą (su) dangčiu. Stalas baltai <b>dengtas</b>.</i>",),
                    "traukti, gobti",
                    ("<i>Debesys <b>dengia</b> dangų. Sniegas <b>dengė</b> žemę.</i>",),
                    "dėti (stogą), stiegti",
                    ("<i>Stogas čerpėmis <b>dengtas</b>. Dangumi <b>dengtas</b> (be stogo).</i>",),
                    "aprūpinti drabužiais, rengti",
                    ("<i>Jį giminės <b>dengia</b> ir maitina.</i>",),
                    "(<i>prk.</i>) ginti, užstoti, slėpti",
                    ("<i>Kas nusikaltėlį <b>dengia</b>? Kulkosvaidžiu <b>dengė</b> atsitraukiantį dalinį.</i>",),
                    "(<i>Sportas</i>) - neleisti laisvai veikti varžovų puolėjui",
                    ("<i>Puolė gerai, bet <b>dengė</b> prastai.</i>",),
                    "(<i>šnek.</i>) greitai, smarkiai ką daryti (eiti, bėgti, važiuoti; mušti, trenkti, rėžti; valgyti, gerti)",
                ],
                "Dalyvis": ["tas kurį dengė"],
                "Sinonimai": ["bėgti", "kloti", "pleikti&nbsp;(<i>tarm.</i>)", "rengti", "smogti", "stiegti", "tiesti"],
            },
            [],
            [
                "dengdama",
                "dengdamas",
                "dengdavai",
                "dengdavau",
                "dengdavo",
                "dengdavom",
                "dengdavome",
                "dengdavot",
                "dengdavote",
                "dengdavus",
                "dengdavusi",
                "dengdavęs",
                "dengei",
                "dengi",
                "dengia",
                "dengiam",
                "dengiama",
                "dengiamas",
                "dengiame",
                "dengiant",
                "dengianti",
                "dengiantis",
                "dengiat",
                "dengiate",
                "dengiau",
                "dengiu",
                "dengiąs",
                "dengs",
                "dengsi",
                "dengsiant",
                "dengsianti",
                "dengsiantis",
                "dengsim",
                "dengsima",
                "dengsimas",
                "dengsime",
                "dengsit",
                "dengsite",
                "dengsiu",
                "dengsiąs",
                "dengta",
                "dengtas",
                "dengte",
                "dengtina",
                "dengtinai",
                "dengtinas",
                "dengtum",
                "dengtume",
                "dengtumei",
                "dengtumėm",
                "dengtumėme",
                "dengtumėt",
                "dengtumėte",
                "dengtų",
                "dengus",
                "dengusi",
                "dengčiau",
                "dengė",
                "dengėm",
                "dengėme",
                "dengėt",
                "dengėte",
                "dengęs",
                "denk",
                "denki",
                "denkim",
                "denkime",
                "denkit",
                "denkite",
                "tedengia",
                "tedengie",
            ],
        ),
        (
            "informatyvus",
            [],
            ["m"],
            ["informuoti + -atyv"],
            {"Būdvardis": ["teikiantis daug informacijos"]},
            [],
            [
                "informatyvaus",
                "informatyvesne",
                "informatyvesnei",
                "informatyvesnes",
                "informatyvesni",
                "informatyvesniais",
                "informatyvesniaisiais",
                "informatyvesniajai",
                "informatyvesniajam",
                "informatyvesniajame",
                "informatyvesniam",
                "informatyvesniame",
                "informatyvesnieji",
                "informatyvesniems",
                "informatyvesniesiems",
                "informatyvesnio",
                "informatyvesnioji",
                "informatyvesniojo",
                "informatyvesniojoje",
                "informatyvesniosiomis",
                "informatyvesniosioms",
                "informatyvesniosios",
                "informatyvesniosiose",
                "informatyvesnis",
                "informatyvesniu",
                "informatyvesniuoju",
                "informatyvesniuose",
                "informatyvesniuosiuose",
                "informatyvesniuosius",
                "informatyvesnius",
                "informatyvesniąja",
                "informatyvesniąją",
                "informatyvesniąsias",
                "informatyvesnių",
                "informatyvesniųjų",
                "informatyvesnysis",
                "informatyvesnė",
                "informatyvesnėje",
                "informatyvesnėmis",
                "informatyvesnėms",
                "informatyvesnės",
                "informatyvesnėse",
                "informatyvesnę",
                "informatyvesnį",
                "informatyvesnįjį",
                "informatyvi",
                "informatyvia",
                "informatyviai",
                "informatyviais",
                "informatyviaisiais",
                "informatyviajai",
                "informatyviajam",
                "informatyviajame",
                "informatyviam",
                "informatyviame",
                "informatyvias",
                "informatyviau",
                "informatyviausi",
                "informatyviausia",
                "informatyviausiai",
                "informatyviausiais",
                "informatyviausiaisiais",
                "informatyviausiajai",
                "informatyviausiajam",
                "informatyviausiajame",
                "informatyviausiam",
                "informatyviausiame",
                "informatyviausias",
                "informatyviausiasis",
                "informatyviausieji",
                "informatyviausiems",
                "informatyviausiesiems",
                "informatyviausio",
                "informatyviausioje",
                "informatyviausioji",
                "informatyviausiojo",
                "informatyviausiojoje",
                "informatyviausiomis",
                "informatyviausioms",
                "informatyviausios",
                "informatyviausiose",
                "informatyviausiosiomis",
                "informatyviausiosioms",
                "informatyviausiosios",
                "informatyviausiosiose",
                "informatyviausiu",
                "informatyviausiuoju",
                "informatyviausiuose",
                "informatyviausiuosiuose",
                "informatyviausiuosius",
                "informatyviausius",
                "informatyviausią",
                "informatyviausiąja",
                "informatyviausiąją",
                "informatyviausiąjį",
                "informatyviausiąsias",
                "informatyviausių",
                "informatyviausiųjų",
                "informatyvieji",
                "informatyviem",
                "informatyviems",
                "informatyviesiem",
                "informatyviesiems",
                "informatyvioj",
                "informatyvioje",
                "informatyvioji",
                "informatyviojo",
                "informatyviojoj",
                "informatyviojoje",
                "informatyviom",
                "informatyviomis",
                "informatyvioms",
                "informatyvios",
                "informatyviose",
                "informatyviosiom",
                "informatyviosiomis",
                "informatyviosioms",
                "informatyviosios",
                "informatyviosiose",
                "informatyviu",
                "informatyviuoju",
                "informatyviuos",
                "informatyviuose",
                "informatyviuosiuos",
                "informatyviuosiuose",
                "informatyviuosius",
                "informatyvius",
                "informatyvią",
                "informatyviąja",
                "informatyviąją",
                "informatyviąsias",
                "informatyvių",
                "informatyviųjų",
                "informatyvu",
                "informatyvusis",
                "informatyvūs",
                "informatyvų",
                "informatyvųjį",
            ],
        ),
        (
            "pasaulis",
            [],
            ["m"],
            [],
            {
                "Daiktavardis": ["visa žemė; Žemės rutulys", "visi žmonės; aplinkiniai žmonės", "visata"],
                "Simbolis": ["🜨, ♁"],
            },
            [],
            [
                "pasauli",
                "pasauliai",
                "pasauliais",
                "pasauliams",
                "pasaulio",
                "pasauliu",
                "pasauliui",
                "pasauliuose",
                "pasaulius",
                "pasaulių",
                "pasaulyje",
                "pasaulį",
            ],
        ),
        (
            "senas",
            ["[ˈsʲæːnɐs]"],
            ["f", "m"],
            [
                "Iš Iš indoeuropiečių prokalbės *sénos. Plg. senovės graikų k. <i>ἕνος</i> (henos), sanskrito सन (sána) ir gotų k. 𐍃𐌹𐌽𐌴𐌹𐌲𐍃 (sineigs)."
            ],
            {
                "Būdvardis": [
                    "jau kuris laikas esantis",
                    "ilgai vartotas, palaikis",
                    "anksčiau buvęs, nedabartinis, pasenęs",
                    "prieš tai buvęs",
                    "pabuvęs, palaikytas, pastovėjęs",
                ],
                "Sinonimai": ["archajiškas", "nejaunas"],
            },
            [],
            [
                "sena",
                "senai",
                "senais",
                "senaisiais",
                "senajai",
                "senajam",
                "senajame",
                "senam",
                "sename",
                "senasis",
                "senesne",
                "senesnei",
                "senesnes",
                "senesni",
                "senesniais",
                "senesniaisiais",
                "senesniajai",
                "senesniajam",
                "senesniajame",
                "senesniam",
                "senesniame",
                "senesnieji",
                "senesniems",
                "senesniesiems",
                "senesnio",
                "senesnioji",
                "senesniojo",
                "senesniojoje",
                "senesniosiomis",
                "senesniosioms",
                "senesniosios",
                "senesniosiose",
                "senesnis",
                "senesniu",
                "senesniuoju",
                "senesniuose",
                "senesniuosiuose",
                "senesniuosius",
                "senesnius",
                "senesniąja",
                "senesniąją",
                "senesniąsias",
                "senesnių",
                "senesniųjų",
                "senesnysis",
                "senesnė",
                "senesnėje",
                "senesnėmis",
                "senesnėms",
                "senesnės",
                "senesnėse",
                "senesnę",
                "senesnį",
                "senesnįjį",
                "seni",
                "seniau",
                "seniausi",
                "seniausia",
                "seniausiai",
                "seniausiais",
                "seniausiaisiais",
                "seniausiajai",
                "seniausiajam",
                "seniausiajame",
                "seniausiam",
                "seniausiame",
                "seniausias",
                "seniausiasis",
                "seniausieji",
                "seniausiems",
                "seniausiesiems",
                "seniausio",
                "seniausioje",
                "seniausioji",
                "seniausiojo",
                "seniausiojoje",
                "seniausiomis",
                "seniausioms",
                "seniausios",
                "seniausiose",
                "seniausiosiomis",
                "seniausiosioms",
                "seniausiosios",
                "seniausiosiose",
                "seniausiu",
                "seniausiuoju",
                "seniausiuose",
                "seniausiuosiuose",
                "seniausiuosius",
                "seniausius",
                "seniausią",
                "seniausiąja",
                "seniausiąją",
                "seniausiąjį",
                "seniausiąsias",
                "seniausių",
                "seniausiųjų",
                "senieji",
                "seniem",
                "seniems",
                "seniesiem",
                "seniesiems",
                "seno",
                "senoj",
                "senoje",
                "senoji",
                "senojo",
                "senojoj",
                "senojoje",
                "senom",
                "senomis",
                "senoms",
                "senos",
                "senose",
                "senosiom",
                "senosiomis",
                "senosioms",
                "senosios",
                "senosiose",
                "senu",
                "senuoju",
                "senuos",
                "senuose",
                "senuosiuos",
                "senuosiuose",
                "senuosius",
                "senus",
                "seną",
                "senąja",
                "senąją",
                "senąjį",
                "senąsias",
                "senų",
                "senųjų",
            ],
        ),
    ],
)
def test_parse_word(
    word: str,
    pronunciations: list[str],
    genders: list[str],
    etymology: list[Definitions],
    definitions: list[Definitions],
    variants: list[str],
    reverse_variants: list[str],
    page: Callable[[str, str], str],
) -> None:
    """Test the sections finder and definitions getter."""
    code = page(word, "lt")
    details = parse_word(word, code, "lt", force=True)
    assert details
    assert pronunciations == details.pronunciations
    assert genders == details.genders
    assert etymology == details.etymology
    assert definitions == details.definitions
    assert variants == details.variants
    assert reverse_variants == details.reverse_variants


def test_skip_variant(page: Callable[[str, str], str]) -> None:
    word = "informatikos"
    code = page(word, "lt")
    details = parse_word(word, code, "lt", force=True)
    assert not details
