import re
from collections import OrderedDict
from collections.abc import Callable
from pathlib import Path
from unittest.mock import patch

import pytest

from wikidict import context
from wikidict.render import parse_word
from wikidict.stubs import Definitions

LANG = __name__.split("_", 1)[1]


@pytest.fixture(scope="module", autouse=True)
def setup_lua_ctx() -> None:
    with patch.dict("os.environ", {"CWD": str(Path(context.__file__).parent.parent)}):
        assert context.reset(LANG)


@pytest.mark.parametrize(
    "word, pronunciations, etymology, definitions, variants, reverse_variants",
    [
        (
            "agitandus",
            ["Class.: /agiˈtandus/"],
            [],
            {},
            ["agito"],
            [
                "agitanda",
                "agitandae",
                "agitandam",
                "agitandarum",
                "agitandas",
                "agitande",
                "agitandi",
                "agitandis",
                "agitando",
                "agitandorum",
                "agitandos",
                "agitandum",
            ],
        ),
        (
            "amarus",
            ["Class.: /aˈmaːrus/", "Eccl.: /aˈmarus/"],
            [],
            {"Nomen Adiectivum": ["Acerbus; sapore absinthii vel quininae."]},
            [],
            [
                "amara",
                "amarae",
                "amaram",
                "amararum",
                "amaras",
                "amare",
                "amari",
                "amarior",
                "amariora",
                "amariore",
                "amariorem",
                "amariores",
                "amariori",
                "amarioribus",
                "amarioris",
                "amariorum",
                "amaris",
                "amarissima",
                "amarissimae",
                "amarissimam",
                "amarissimarum",
                "amarissimas",
                "amarissime",
                "amarissimi",
                "amarissimis",
                "amarissimo",
                "amarissimorum",
                "amarissimos",
                "amarissimum",
                "amarissimus",
                "amarius",
                "amaro",
                "amarorum",
                "amaros",
                "amarum",
            ],
        ),
        (
            "Gaius Plinius Secundus",
            [],
            [],
            {"Nomen Proprium|m.": ["Vir doctus, scriptor, 23 – 79 p. Chr. n."]},
            [],
            [],
        ),
        (
            "gero",
            ["Class.: /ˈgeroː/"],
            [],
            {
                "Verbum Transitivum": ["√ Portare, ferre.", "Agere, facere."],
                "Nomen Substantivum|m.": ["Qui gerit."],
            },
            [],
            [
                "geram",
                "geramini",
                "geramur",
                "geramus",
                "gerant",
                "gerantur",
                "gerar",
                "geraris",
                "geras",
                "gerat",
                "geratis",
                "geratur",
                "gere",
                "gerebam",
                "gerebamini",
                "gerebamur",
                "gerebamus",
                "gerebant",
                "gerebantur",
                "gerebar",
                "gerebaris",
                "gerebas",
                "gerebat",
                "gerebatis",
                "gerebatur",
                "geremini",
                "geremur",
                "geremus",
                "gerendi",
                "gerendus",
                "gerens",
                "gerent",
                "gerentur",
                "gerere",
                "gererem",
                "gereremini",
                "gereremur",
                "gereremus",
                "gererent",
                "gererentur",
                "gererer",
                "gerereris",
                "gereres",
                "gereret",
                "gereretis",
                "gereretur",
                "gereris",
                "geres",
                "geret",
                "geretis",
                "geretur",
                "geri",
                "gerimini",
                "gerimur",
                "gerimus",
                "geris",
                "gerit",
                "gerite",
                "geritis",
                "gerito",
                "geritor",
                "geritote",
                "geritur",
                "geror",
                "gerunt",
                "gerunto",
                "geruntor",
                "geruntur",
                "gesseram",
                "gesseramus",
                "gesserant",
                "gesseras",
                "gesserat",
                "gesseratis",
                "gessere",
                "gesserim",
                "gesserimus",
                "gesserint",
                "gesseris",
                "gesserit",
                "gesseritis",
                "gessero",
                "gesserunt",
                "gessi",
                "gessimus",
                "gessisse",
                "gessissem",
                "gessissemus",
                "gessissent",
                "gessisses",
                "gessisset",
                "gessissetis",
                "gessisti",
                "gessistis",
                "gessit",
                "gestu",
                "gestum",
                "gesturum",
                "gesturus",
                "gestus",
            ],
        ),
        (
            "hilariter",
            ["Class.: /hiˈla.ri.ter/"],
            [],
            {
                "Adverbium": ["Cum hilaritate."],
                "Synonyma": ["hilarē"],
            },
            [],
            [],
        ),
        ("quum", [], [], {}, ["cum"], []),
        (
            "sugo",
            [],
            ["Cognata est vox Anglica <b>suck</b>."],
            {"Verbum Transitivum": ["Imbibere liquidum per os trahendo, ut per mammam."]},
            [],
            [
                "suctu",
                "suctum",
                "sucturus",
                "suctus",
                "sugam",
                "sugamini",
                "sugamur",
                "sugamus",
                "sugant",
                "sugantur",
                "sugar",
                "sugaris",
                "sugas",
                "sugat",
                "sugatis",
                "sugatur",
                "suge",
                "sugebam",
                "sugebamini",
                "sugebamur",
                "sugebamus",
                "sugebant",
                "sugebantur",
                "sugebar",
                "sugebaris",
                "sugebas",
                "sugebat",
                "sugebatis",
                "sugebatur",
                "sugemini",
                "sugemur",
                "sugemus",
                "sugendum",
                "sugendus",
                "sugens",
                "sugent",
                "sugentur",
                "sugere",
                "sugerem",
                "sugeremini",
                "sugeremur",
                "sugeremus",
                "sugerent",
                "sugerentur",
                "sugerer",
                "sugereris",
                "sugeres",
                "sugeret",
                "sugeretis",
                "sugeretur",
                "sugeris",
                "suges",
                "suget",
                "sugetis",
                "sugetur",
                "sugi",
                "sugimini",
                "sugimur",
                "sugimus",
                "sugis",
                "sugit",
                "sugite",
                "sugitis",
                "sugito",
                "sugitor",
                "sugitote",
                "sugitur",
                "sugor",
                "sugunt",
                "sugunto",
                "suguntor",
                "suguntur",
                "suxeram",
                "suxeramus",
                "suxerant",
                "suxeras",
                "suxerat",
                "suxeratis",
                "suxerim",
                "suxerimus",
                "suxerint",
                "suxeris",
                "suxerit",
                "suxeritis",
                "suxero",
                "suxerunt",
                "suxi",
                "suximus",
                "suxisse",
                "suxissem",
                "suxissemus",
                "suxissent",
                "suxisses",
                "suxisset",
                "suxissetis",
                "suxisti",
                "suxistis",
                "suxit",
            ],
        ),
        (
            "sum",
            ["Class.: /sum/"],
            [
                "A lingua prisca Indoeuropaea <i>*H₁es-</i> (praesens) et <i>*bhu-</i> (perfecta). Vide radicem <i>es</i> et radicem <i>fu</i>."
            ],
            {
                "Verbum": [
                    "<i>(Intransitivum)</i> exsisto in vero",
                    "<i>(Auxiliare)</i> verbum copulativum, qui existere in aliquo modo vel aliquo relatione indicat.",
                ],
                "Synonyma": ["exsistō"],
            },
            [],
            [
                "ens",
                "eram",
                "eramus",
                "erant",
                "eras",
                "erat",
                "eratis",
                "erimus",
                "eris",
                "erit",
                "eritis",
                "ero",
                "erunt",
                "es",
                "esse",
                "essem",
                "essemus",
                "essent",
                "esses",
                "esset",
                "essetis",
                "est",
                "este",
                "estis",
                "esto",
                "estote",
                "fore",
                "forem",
                "foremus",
                "forent",
                "fores",
                "foret",
                "foretis",
                "fueram",
                "fueramus",
                "fuerant",
                "fueras",
                "fuerat",
                "fueratis",
                "fuerim",
                "fuerimus",
                "fuerint",
                "fueris",
                "fuerit",
                "fueritis",
                "fuero",
                "fuerunt",
                "fui",
                "fuimus",
                "fuisse",
                "fuissem",
                "fuissemus",
                "fuissent",
                "fuisses",
                "fuisset",
                "fuissetis",
                "fuisti",
                "fuistis",
                "fuit",
                "futurum",
                "futurus",
                "sim",
                "simus",
                "sint",
                "sis",
                "sit",
                "sitis",
                "sumus",
                "sunt",
                "sunto",
            ],
        ),
        (
            "turris",
            [],
            [],
            {"Nomen Substantivum|f.": ["Alta domus, palatium, arx"]},
            [],
            ["turres", "turri", "turribus", "turrim", "turrium"],
        ),
    ],
)
def test_parse_word(
    word: str,
    pronunciations: list[str],
    etymology: list[Definitions],
    definitions: Definitions,
    variants: list[str],
    reverse_variants: list[str],
    page: Callable[[str, str], str],
) -> None:
    """Test the sections finder and definitions getter."""
    code = page(word, LANG)

    # Needs specific transformations before hand (they are done in --parse & --get-word, but this is not a taken path by the test)
    # `{{lingua2|la|Gaius Plinius Secundus}}` → `=={{-la-}}==`
    code = re.sub(r"^\{\{lingua2\|([^|}]+).*", r"=={{-\1-}}==", code, flags=re.MULTILINE)
    # `=={{int:wikt-affines}}==` → `==={{int:wikt-affines}}===`
    code = code.replace("=={{int:wikt-affines}}==", "==={{int:wikt-affines}}===", count=1)

    details = parse_word(word, code, LANG, force=True)
    assert details
    assert pronunciations == details.pronunciations
    assert etymology == details.etymology
    assert OrderedDict(definitions) == details.definitions
    assert variants == details.variants
    assert reverse_variants == details.reverse_variants

    assert not context.get_then_clear_errors()
